version: '3.1'

services:
  db:
    image: mysql:8.3.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    ports:
      - 3306:3306